// Données de démo — Midi Nautisme & Locamotors — Vieux-Port Marseille

export const BRANDS = {
  'midi-nautisme': {
    id: 'midi-nautisme',
    name: 'Midi Nautisme',
    tagline: 'Voiliers & Catamarans',
    port: 'Quai de la Criée, Vieux-Port — Marseille',
    phone: '04 91 54 86 09',
    email: 'info@midinautisme.fr',
    color: 'navy',
    accent: '#185FA5',
    logo: 'MN',
  },
  'locamotors': {
    id: 'locamotors',
    name: 'Locamotors',
    tagline: 'Semi-rigides & Moteurs',
    port: 'Panne Saint Jean, Vieux-Port — Marseille',
    phone: '04 91 54 86 09',
    email: 'info@locamotors.fr',
    color: 'teal',
    accent: '#1D9E75',
    logo: 'LM',
  },
}

export const BOATS = [
  // MIDI NAUTISME — Voiliers Dufour
  {
    id: 'mn-1',
    brand: 'midi-nautisme',
    name: 'Dufour 360',
    type: 'Voilier',
    length: 11,
    port: 'Quai de la Criée',
    docs: {
      francisation: { status: 'ok', expires: '2027-03-15', label: 'À jour' },
      assurance:    { status: 'warn', expires: '2026-07-17', label: 'Expire 17 juil.' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-2',
    brand: 'midi-nautisme',
    name: 'Dufour 390',
    type: 'Voilier',
    length: 12,
    port: 'Quai de la Criée',
    docs: {
      francisation: { status: 'danger', expires: null, label: 'Manquante' },
      assurance:    { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-3',
    brand: 'midi-nautisme',
    name: 'Dufour 412',
    type: 'Voilier',
    length: 12.5,
    port: 'Quai de la Criée',
    docs: {
      francisation: { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      assurance:    { status: 'warn', expires: '2026-08-02', label: 'Expire 2 août' },
      securite:     { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  // MIDI NAUTISME — Catamarans
  {
    id: 'mn-4',
    brand: 'midi-nautisme',
    name: 'Elba 45',
    type: 'Catamaran',
    length: 13.5,
    port: 'Quai de la Criée',
    docs: {
      francisation: { status: 'ok', expires: '2027-06-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-15', label: 'À jour' },
      securite:     { status: 'warn', expires: '2026-07-30', label: 'Expire 30j' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-5',
    brand: 'midi-nautisme',
    name: 'Astrea 42',
    type: 'Catamaran',
    length: 12.8,
    port: 'Quai de la Criée',
    docs: {
      francisation: { status: 'ok', expires: '2027-04-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  // LOCAMOTORS — Semi-rigides
  {
    id: 'lm-1',
    brand: 'locamotors',
    name: 'Tempest 505',
    type: 'Semi-rigide',
    length: 5,
    port: 'Panne Saint Jean',
    docs: {
      francisation: { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      assurance:    { status: 'danger', expires: null, label: 'Manquante' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'lm-2',
    brand: 'locamotors',
    name: 'BSC 65',
    type: 'Semi-rigide',
    length: 6.5,
    port: 'Panne Saint Jean',
    docs: {
      francisation: { status: 'ok', expires: '2027-02-01', label: 'À jour' },
      assurance:    { status: 'warn', expires: '2026-07-20', label: 'Expire 20 juil.' },
      securite:     { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'lm-3',
    brand: 'locamotors',
    name: 'BSC 70',
    type: 'Semi-rigide',
    length: 7,
    port: 'Panne Saint Jean',
    docs: {
      francisation: { status: 'ok', expires: '2027-03-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  // LOCAMOTORS — Moteurs
  {
    id: 'lm-4',
    brand: 'locamotors',
    name: 'Pacific Craft 730',
    type: 'Moteur',
    length: 7.3,
    port: 'Panne Saint Jean',
    docs: {
      francisation: { status: 'danger', expires: null, label: 'Manquante' },
      assurance:    { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'lm-5',
    brand: 'locamotors',
    name: 'Hanse 510',
    type: 'Moteur',
    length: 5.1,
    port: 'Panne Saint Jean',
    docs: {
      francisation: { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-08-15', label: 'À jour' },
      securite:     { status: 'warn', expires: '2026-07-25', label: 'Expire 25j' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
]

export const SKIPPERS = [
  {
    id: 'skip-1',
    name: 'Jean-Marc Rossi',
    initials: 'JM',
    location: 'Marseille',
    rating: 4.9,
    missions: 38,
    rate: 180,
    available: true,
    color: 'bg-navy-100 text-navy-800',
    permis: ['Côtier', 'Hauturier', 'CRR', 'STCW'],
    boats: ['Voilier', 'Catamaran'],
    phone: '06 44 55 66 77',
    reviews: [
      { agency: 'Midi Nautisme', stars: 5, text: 'Ponctuel, clients très satisfaits. On le rappelle à chaque saison.' },
      { agency: 'Locamotors', stars: 5, text: 'Excellent contact avec les familles. Recommandé sans hésitation.' },
    ],
    availability: {
      busy: ['2026-07-04','2026-07-05','2026-07-06','2026-07-07','2026-07-08',
             '2026-07-09','2026-07-10','2026-07-11','2026-07-12'],
    },
  },
  {
    id: 'skip-2',
    name: 'Sophie Bernard',
    initials: 'SB',
    location: 'La Ciotat',
    rating: 4.6,
    missions: 22,
    rate: 150,
    available: true,
    color: 'bg-teal-50 text-teal-800',
    permis: ['Côtier', 'CRR'],
    boats: ['Voilier', 'Semi-rigide'],
    phone: '06 22 33 44 55',
    reviews: [
      { agency: 'Midi Nautisme', stars: 5, text: 'Très à l\'aise avec les débutants, rassurante.' },
    ],
    availability: { busy: [] },
  },
  {
    id: 'skip-3',
    name: 'Thomas Lebrun',
    initials: 'TL',
    location: 'Toulon',
    rating: 5.0,
    missions: 61,
    rate: 220,
    available: false,
    color: 'bg-amber-50 text-amber-800',
    permis: ['Côtier', 'Hauturier', 'CRR', 'Yachtmaster'],
    boats: ['Voilier', 'Catamaran', 'Moteur'],
    phone: '06 77 88 99 00',
    reviews: [
      { agency: 'Midi Nautisme', stars: 5, text: 'Le meilleur skipper qu\'on ait eu. Clients toujours ravis.' },
    ],
    availability: { busy: [] },
  },
]

export const BOOKINGS = [
  {
    id: 'bk-1',
    boatId: 'mn-1',
    boatName: 'Dufour 360',
    brand: 'midi-nautisme',
    client: 'Moreau Jean',
    phone: '06 12 34 56 78',
    guests: '4 adultes, 1 enfant',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: 'skip-1',
    skipperName: 'Jean-Marc Rossi',
    skipperInitials: 'JM',
    needsSkipper: true,
    draps: [
      { name: 'Grand lit 160×200', qty: 1, unit: 'jeu' },
      { name: 'Simples 90×200', qty: 2, unit: 'jeux' },
      { name: 'Taies 65×65', qty: 5, unit: 'pièces' },
      { name: 'Serviettes bain', qty: 5, unit: 'pièces' },
    ],
    status: 'confirmed',
    color: 'teal',
  },
  {
    id: 'bk-2',
    boatId: 'mn-4',
    boatName: 'Elba 45',
    brand: 'midi-nautisme',
    client: 'Bernard Laurent',
    phone: '07 11 22 33 44',
    guests: '6 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: 'skip-2',
    skipperName: 'Sophie Bernard',
    skipperInitials: 'SB',
    needsSkipper: true,
    draps: [
      { name: 'Grand lit 160×200', qty: 2, unit: 'jeux' },
      { name: 'Taies 65×65', qty: 6, unit: 'pièces' },
    ],
    status: 'confirmed',
    color: 'teal',
  },
  {
    id: 'bk-3',
    boatId: 'mn-2',
    boatName: 'Dufour 390',
    brand: 'midi-nautisme',
    client: 'Martin Pierre',
    phone: '06 55 44 33 22',
    guests: '3 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: null,
    skipperName: null,
    needsSkipper: false,
    draps: [],
    status: 'doc-issue',
    color: 'danger',
  },
  {
    id: 'bk-4',
    boatId: 'lm-1',
    boatName: 'Tempest 505',
    brand: 'locamotors',
    client: 'Legrand François',
    phone: '06 77 88 99 00',
    guests: '4 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: null,
    skipperName: null,
    needsSkipper: true,
    draps: [],
    status: 'skipper-missing',
    color: 'amber',
  },
  {
    id: 'bk-5',
    boatId: 'lm-4',
    boatName: 'Pacific Craft 730',
    brand: 'locamotors',
    client: 'Dupont Marie',
    phone: '06 33 22 11 00',
    guests: '5 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: null,
    skipperName: null,
    needsSkipper: false,
    draps: [],
    status: 'doc-issue',
    color: 'danger',
  },
]

export const TECHNICIANS = [
  {
    id: 'tech-1',
    name: 'Karim B.',
    assignedBoats: ['mn-1'],
    tasks: {
      'mn-1': [
        { id: 't1', label: 'Nettoyage cabines', done: true },
        { id: 't2', label: 'Draps posés (3 jeux)', done: true },
        { id: 't3', label: 'Inventaire vérifié', done: true },
        { id: 't4', label: 'Équipements sécurité', done: false },
      ],
    },
  },
  {
    id: 'tech-2',
    name: 'Léa M.',
    assignedBoats: ['lm-1'],
    tasks: {
      'lm-1': [
        { id: 't5', label: 'Nettoyage cockpit', done: true },
        { id: 't6', label: 'Inventaire vérifié', done: false },
        { id: 't7', label: 'Carburant fait le plein', done: false },
        { id: 't8', label: 'Équipements sécurité', done: false },
      ],
    },
  },
]

export const DOC_LABELS = {
  francisation: 'Francisation',
  assurance:    'Assurance',
  securite:     'Carnet sécurité',
  jauge:        'Jauge officielle',
}
