// Données de démo — à remplacer par Supabase en production

export const AGENCY = {
  id: 'agency-1',
  name: 'Midi Nautisme',
  port: 'Marseille',
  email: 'contact@midinautisme.fr',
  phone: '04 91 12 34 56',
}

export const BOATS = [
  {
    id: 'boat-1',
    name: 'Bella Mare',
    type: 'Voilier',
    length: 10,
    port: 'Marseille',
    docs: {
      francisation: { status: 'ok', expires: '2027-03-15', label: 'À jour' },
      assurance:    { status: 'warn', expires: '2026-07-17', label: 'Expire 17 juil.' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'boat-2',
    name: 'Timéo II',
    type: 'Catamaran',
    length: 12,
    port: 'Marseille',
    docs: {
      francisation: { status: 'ok', expires: '2027-06-01', label: 'À jour' },
      assurance:    { status: 'warn', expires: '2026-07-07', label: 'Expire 12j' },
      securite:     { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'boat-3',
    name: 'Cap Mistral',
    type: 'Moteur',
    length: 8,
    port: 'Marseille',
    docs: {
      francisation: { status: 'danger', expires: null, label: 'Manquante' },
      assurance:    { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'boat-4',
    name: 'Le Phocéen',
    type: 'Voilier',
    length: 9,
    port: 'Marseille',
    docs: {
      francisation: { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-01', label: 'À jour' },
      securite:     { status: 'warn', expires: '2026-07-25', label: 'Expire 30j' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
]

export const SKIPPERS = [
  {
    id: 'skip-1',
    name: 'Jean-Marc Rossi',
    initials: 'JM',
    location: 'Marseille',
    rating: 4.9,
    missions: 38,
    rate: 180,
    available: true,
    color: 'bg-navy-100 text-navy-800',
    permis: ['Côtier', 'Hauturier', 'CRR', 'STCW'],
    boats: ['Voilier', 'Catamaran', 'Moteur'],
    phone: '06 44 55 66 77',
    reviews: [
      { agency: 'Midi Nautisme', stars: 5, text: 'Ponctuel, clients très satisfaits. On le rappelle à chaque saison.' },
      { agency: 'Azur Loc Voile', stars: 5, text: 'Excellent contact avec les familles. Recommandé sans hésitation.' },
    ],
    availability: {
      busy: ['2026-07-04','2026-07-05','2026-07-06','2026-07-07','2026-07-08',
             '2026-07-09','2026-07-10','2026-07-11','2026-07-12','2026-07-18',
             '2026-07-19','2026-07-20','2026-07-21','2026-07-22','2026-07-23',
             '2026-07-24','2026-07-25','2026-07-26'],
    },
  },
  {
    id: 'skip-2',
    name: 'Sophie Bernard',
    initials: 'SB',
    location: 'La Ciotat',
    rating: 4.6,
    missions: 22,
    rate: 150,
    available: true,
    color: 'bg-teal-50 text-teal-800',
    permis: ['Côtier', 'CRR'],
    boats: ['Voilier'],
    phone: '06 22 33 44 55',
    reviews: [
      { agency: 'Midi Nautisme', stars: 5, text: 'Très à l\'aise avec les débutants, rassurante.' },
    ],
    availability: { busy: [] },
  },
  {
    id: 'skip-3',
    name: 'Thomas Lebrun',
    initials: 'TL',
    location: 'Toulon',
    rating: 5.0,
    missions: 61,
    rate: 220,
    available: false,
    color: 'bg-amber-50 text-amber-800',
    permis: ['Côtier', 'Hauturier', 'CRR', 'Yachtmaster'],
    boats: ['Voilier', 'Catamaran'],
    phone: '06 77 88 99 00',
    reviews: [
      { agency: 'Cap Nautic', stars: 5, text: 'Le meilleur skipper que j\'ai eu sur mes bateaux.' },
    ],
    availability: { busy: [] },
  },
]

export const BOOKINGS = [
  {
    id: 'bk-1',
    boatId: 'boat-1',
    boatName: 'Bella Mare',
    client: 'Moreau Jean',
    phone: '06 12 34 56 78',
    guests: '4 adultes, 1 enfant',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: 'skip-1',
    skipperName: 'Jean-Marc Rossi',
    skipperInitials: 'JM',
    needsSkipper: true,
    draps: [
      { name: 'Grand lit 160×200', qty: 1, unit: 'jeu' },
      { name: 'Simples 90×200', qty: 2, unit: 'jeux' },
      { name: 'Taies 65×65', qty: 5, unit: 'pièces' },
      { name: 'Serviettes bain', qty: 5, unit: 'pièces' },
      { name: 'Serviettes plage', qty: 5, unit: 'pièces' },
      { name: 'Torchons', qty: 4, unit: 'pièces' },
    ],
    status: 'confirmed',
    color: 'teal',
  },
  {
    id: 'bk-2',
    boatId: 'boat-2',
    boatName: 'Timéo II',
    client: 'Bernard Laurent',
    phone: '07 11 22 33 44',
    guests: '6 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: 'skip-2',
    skipperName: 'Sophie Bernard',
    skipperInitials: 'SB',
    needsSkipper: true,
    draps: [
      { name: 'Grand lit 160×200', qty: 2, unit: 'jeux' },
      { name: 'Simples 90×200', qty: 2, unit: 'jeux' },
      { name: 'Taies 65×65', qty: 6, unit: 'pièces' },
    ],
    status: 'confirmed',
    color: 'teal',
  },
  {
    id: 'bk-3',
    boatId: 'boat-3',
    boatName: 'Cap Mistral',
    client: 'Martin Pierre',
    phone: '06 55 44 33 22',
    guests: '3 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: null,
    skipperName: null,
    needsSkipper: false,
    draps: [],
    status: 'doc-issue',
    color: 'danger',
  },
  {
    id: 'bk-4',
    boatId: 'boat-4',
    boatName: 'Le Phocéen',
    client: 'Legrand François',
    phone: '06 77 88 99 00',
    guests: '4 adultes',
    start: '2026-07-05',
    end: '2026-07-12',
    skipperId: null,
    skipperName: null,
    needsSkipper: true,
    draps: [
      { name: 'Grand lit 160×200', qty: 1, unit: 'jeu' },
      { name: 'Simples 90×200', qty: 2, unit: 'jeux' },
    ],
    status: 'skipper-missing',
    color: 'amber',
  },
]

export const TECHNICIANS = [
  {
    id: 'tech-1',
    name: 'Karim B.',
    assignedBoats: ['boat-1'],
    tasks: {
      'boat-1': [
        { id: 't1', label: 'Nettoyage cabines', done: true },
        { id: 't2', label: 'Draps posés (3 jeux)', done: true },
        { id: 't3', label: 'Inventaire vérifié', done: true },
        { id: 't4', label: 'Équipements sécurité', done: false },
      ],
    },
  },
  {
    id: 'tech-2',
    name: 'Léa M.',
    assignedBoats: ['boat-4'],
    tasks: {
      'boat-4': [
        { id: 't5', label: 'Nettoyage cockpit', done: true },
        { id: 't6', label: 'Draps posés', done: false, alert: true },
        { id: 't7', label: 'Inventaire vérifié', done: false },
        { id: 't8', label: 'Équipements sécurité', done: false },
      ],
    },
  },
]

export const DOC_LABELS = {
  francisation: 'Francisation',
  assurance:    'Assurance',
  securite:     'Carnet sécurité',
  jauge:        'Jauge officielle',
}
