export const BRANDS = {
  'midi-nautisme': {
    id: 'midi-nautisme',
    name: 'Midi Nautisme',
    tagline: 'Voiliers & Catamarans',
    port: 'Vieux-Port & Port Corbières — Marseille',
    phone: '04 91 54 86 09',
    email: 'info@midinautisme.fr',
    color: 'navy',
    accent: '#185FA5',
    logo: 'MN',
  },
  'locamotors': {
    id: 'locamotors',
    name: 'Locamotors',
    tagline: 'Semi-rigides & Moteurs',
    port: 'Panne Saint Jean, Vieux-Port — Marseille',
    phone: '04 91 54 86 10',
    email: 'info@locamotors.fr',
    color: 'teal',
    accent: '#1D9E75',
    logo: 'LM',
  },
}

export const CLIENTS = [
  {
    id: 'cli-1',
    nom: 'Moreau', prenom: 'Jean',
    tel: '06 12 34 56 78', email: 'jean.moreau@email.com',
    tel2: '06 98 76 54 32',
    naissance: '1978-03-15', nationalite: 'Française',
    pieceId: { numero: 'FR123456789', type: 'CNI', uploaded: true },
    permis: { numero: 'PM-13-2015-042', type: 'Côtier', uploaded: true },
    caution: { montant: 2000, mode: 'CB', statut: 'recue' },
    notes: 'Client fidèle depuis 2019. Très soigneux avec les bateaux.',
    locations: ['bk-1'],
  },
  {
    id: 'cli-2',
    nom: 'Bernard', prenom: 'Laurent',
    tel: '07 11 22 33 44', email: 'l.bernard@email.com',
    tel2: null,
    naissance: '1985-07-22', nationalite: 'Française',
    pieceId: { numero: 'FR987654321', type: 'Passeport', uploaded: true },
    permis: { numero: 'PM-06-2018-117', type: 'Hauturier', uploaded: false },
    caution: { montant: 3000, mode: 'Chèque', statut: 'en_attente' },
    notes: '',
    locations: ['bk-2'],
  },
  {
    id: 'cli-3',
    nom: 'Martin', prenom: 'Pierre',
    tel: '06 55 44 33 22', email: 'pierre.martin@email.com',
    tel2: null,
    naissance: '1990-11-08', nationalite: 'Française',
    pieceId: { numero: '', type: 'CNI', uploaded: false },
    permis: { numero: '', type: 'Côtier', uploaded: false },
    caution: { montant: 2000, mode: 'CB', statut: 'en_attente' },
    notes: 'Premier louage. À surveiller.',
    locations: ['bk-3'],
  },
  {
    id: 'cli-4',
    nom: 'Legrand', prenom: 'François',
    tel: '06 77 88 99 00', email: 'f.legrand@email.com',
    tel2: null,
    naissance: '1972-05-30', nationalite: 'Française',
    pieceId: { numero: 'FR456789123', type: 'CNI', uploaded: true },
    permis: { numero: '', type: '', uploaded: false },
    caution: { montant: 1500, mode: 'CB', statut: 'recue' },
    notes: '',
    locations: ['bk-4'],
  },
  {
    id: 'cli-5',
    nom: 'Faure', prenom: 'Christine',
    tel: '06 33 22 11 00', email: 'c.faure@email.com',
    tel2: '06 12 99 88 77',
    naissance: '1982-04-15', nationalite: 'Française',
    pieceId: { numero: 'FR111222333', type: 'CNI', uploaded: true },
    permis: { numero: 'PM-13-2020-088', type: 'Hauturier', uploaded: true },
    caution: { montant: 3000, mode: 'CB', statut: 'recue' },
    notes: 'Navigatrice expérimentée, loue chaque été.',
    locations: ['bk-5'],
  },
  {
    id: 'cli-6',
    nom: 'Roche', prenom: 'Antoine',
    tel: '06 88 77 66 55', email: 'antoine.roche@email.com',
    tel2: null,
    naissance: '1979-09-12', nationalite: 'Française',
    pieceId: { numero: 'FR222333444', type: 'CNI', uploaded: true },
    permis: { numero: 'PM-13-2017-201', type: 'Côtier', uploaded: true },
    caution: { montant: 2000, mode: 'CB', statut: 'recue' },
    notes: '',
    locations: ['bk-7'],
  },
  {
    id: 'cli-7',
    nom: 'Girard', prenom: 'Sophie',
    tel: '06 44 11 22 33', email: 's.girard@email.com',
    tel2: null,
    naissance: '1988-02-28', nationalite: 'Française',
    pieceId: { numero: 'FR333444555', type: 'Passeport', uploaded: true },
    permis: { numero: '', type: '', uploaded: false },
    caution: { montant: 2500, mode: 'Chèque', statut: 'recue' },
    notes: '',
    locations: ['bk-8'],
  },
  {
    id: 'cli-8',
    nom: 'Lemoine', prenom: 'Thibault',
    tel: '06 99 22 33 44', email: 't.lemoine@email.com',
    tel2: null,
    naissance: '1975-12-03', nationalite: 'Française',
    pieceId: { numero: 'FR444555666', type: 'CNI', uploaded: true },
    permis: { numero: 'PM-13-2012-076', type: 'Hauturier', uploaded: true },
    caution: { montant: 3500, mode: 'CB', statut: 'recue' },
    notes: 'Client VIP — loue régulièrement le Dufour 48.',
    locations: ['bk-9'],
  },
  {
    id: 'cli-9',
    nom: 'Perrin', prenom: 'Claire',
    tel: '06 66 77 88 99', email: 'claire.perrin@email.com',
    tel2: null,
    naissance: '1992-06-19', nationalite: 'Française',
    pieceId: { numero: '', type: 'CNI', uploaded: false },
    permis: { numero: 'PM-83-2021-145', type: 'Côtier', uploaded: true },
    caution: { montant: 2000, mode: 'CB', statut: 'en_attente' },
    notes: '',
    locations: ['bk-10'],
  },
  {
    id: 'cli-10',
    nom: 'Mercier', prenom: 'Olivier',
    tel: '06 55 11 99 22', email: 'olivier.mercier@email.com',
    tel2: null,
    naissance: '1983-10-07', nationalite: 'Française',
    pieceId: { numero: 'FR555666777', type: 'CNI', uploaded: true },
    permis: { numero: '', type: '', uploaded: false },
    caution: { montant: 2200, mode: 'CB', statut: 'recue' },
    notes: '',
    locations: ['bk-11'],
  },
]

export const BOATS = [
  // ── Voiliers Vieux-Port ─────────────────────────────────────────
  {
    id: 'mn-1', brand: 'midi-nautisme', name: 'Dufour 360 GL — Yume',
    type: 'Voilier', modele: 'Dufour 360 GL', length: 10.40, annee: 2021,
    capacite: 8, cabines: 3, lits: 6, port: 'Vieux-Port',
    immat: 'FR-13001-A',
    docs: {
      francisation: { status: 'ok', expires: '2027-03-15', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-17', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-2', brand: 'midi-nautisme', name: 'Dufour 382 GL — Kalliste',
    type: 'Voilier', modele: 'Dufour 382 GL', length: 11.25, annee: 2017,
    capacite: 8, cabines: 3, lits: 6, port: 'Vieux-Port',
    immat: 'FR-13002-B',
    docs: {
      francisation: { status: 'ok', expires: '2027-02-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-3', brand: 'midi-nautisme', name: 'Dufour 390 — Juleroga',
    type: 'Voilier', modele: 'Dufour 390', length: 11.94, annee: 2023,
    capacite: 8, cabines: 3, lits: 6, port: 'Vieux-Port',
    immat: 'FR-13003-C',
    docs: {
      francisation: { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      assurance:    { status: 'warn', expires: '2026-07-25', label: 'Expire 25 juil.' },
      securite:     { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-4', brand: 'midi-nautisme', name: 'Dufour 350',
    type: 'Voilier', modele: 'Dufour 350', length: 10.28, annee: 2016,
    capacite: 8, cabines: 3, lits: 6, port: 'Vieux-Port',
    immat: 'FR-13004-D',
    docs: {
      francisation: { status: 'ok', expires: '2027-06-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-15', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  // ── Catamarans Port Corbières ───────────────────────────────────
  {
    id: 'mn-5', brand: 'midi-nautisme', name: 'Astrea 42 — Bôrev',
    type: 'Catamaran', modele: 'Fountaine Pajot Astrea 42', length: 12.58, annee: 2025,
    capacite: 9, cabines: 4, lits: 8, port: 'Port Corbières',
    immat: 'FR-13005-E',
    docs: {
      francisation: { status: 'ok', expires: '2028-01-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2027-06-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2029-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-6', brand: 'midi-nautisme', name: '460 — L\'After',
    type: 'Catamaran', modele: 'Fountaine Pajot 460', length: 14.60, annee: 2025,
    capacite: 10, cabines: 5, lits: 10, port: 'Port Corbières',
    immat: 'FR-13006-F',
    docs: {
      francisation: { status: 'ok', expires: '2028-01-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2027-09-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2029-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-7', brand: 'midi-nautisme', name: 'Bali 4.1 · 6 cabines',
    type: 'Catamaran', modele: 'Bali 4.1', length: 12.12, annee: 2021,
    capacite: 12, cabines: 6, lits: 12, port: 'Port Corbières',
    immat: 'FR-13007-G',
    docs: {
      francisation: { status: 'ok', expires: '2027-04-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-11-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-8', brand: 'midi-nautisme', name: 'Elba 45 — Sirena',
    type: 'Catamaran', modele: 'Fountaine Pajot Elba 45', length: 13.66, annee: 2022,
    capacite: 10, cabines: 4, lits: 8, port: 'Port Corbières',
    immat: 'FR-13008-H',
    docs: {
      francisation: { status: 'ok', expires: '2027-09-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2027-02-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-9', brand: 'midi-nautisme', name: 'Dufour 48 — Petrel',
    type: 'Voilier', modele: 'Dufour 48', length: 14.40, annee: 2024,
    capacite: 10, cabines: 5, lits: 10, port: 'Vieux-Port',
    immat: 'FR-13009-I',
    docs: {
      francisation: { status: 'ok', expires: '2028-02-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2027-03-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2029-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-10', brand: 'midi-nautisme', name: 'MY40 — Calypso',
    type: 'Catamaran à moteur', modele: 'Fountaine Pajot MY40', length: 12.0, annee: 2023,
    capacite: 8, cabines: 4, lits: 8, port: 'Port Corbières',
    immat: 'FR-13010-J',
    docs: {
      francisation: { status: 'ok', expires: '2027-07-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'mn-11', brand: 'midi-nautisme', name: 'Dufour 41 — Lou Calèu',
    type: 'Voilier', modele: 'Dufour 41', length: 12.5, annee: 2022,
    capacite: 8, cabines: 4, lits: 8, port: 'Vieux-Port',
    immat: 'FR-13011-K',
    docs: {
      francisation: { status: 'ok', expires: '2027-05-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  // ── Locamotors ──────────────────────────────────────────────────
  {
    id: 'lm-1', brand: 'locamotors', name: 'Tempest 505',
    type: 'Semi-rigide', modele: 'Tempest 505', length: 5.0, annee: 2022,
    capacite: 8, cabines: 0, lits: 0, port: 'Panne Saint Jean',
    immat: 'FR-13010-A',
    docs: {
      francisation: { status: 'ok', expires: '2027-01-01', label: 'À jour' },
      assurance:    { status: 'danger', expires: null, label: 'Manquante' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'lm-2', brand: 'locamotors', name: 'BSC 65',
    type: 'Semi-rigide', modele: 'BSC 65', length: 6.5, annee: 2021,
    capacite: 8, cabines: 0, lits: 0, port: 'Panne Saint Jean',
    immat: 'FR-13011-B',
    docs: {
      francisation: { status: 'ok', expires: '2027-02-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-09-20', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
  {
    id: 'lm-3', brand: 'locamotors', name: 'Pacific Craft 730',
    type: 'Moteur', modele: 'Pacific Craft 730', length: 7.3, annee: 2023,
    capacite: 8, cabines: 0, lits: 0, port: 'Panne Saint Jean',
    immat: 'FR-13012-C',
    docs: {
      francisation: { status: 'ok', expires: '2027-08-01', label: 'À jour' },
      assurance:    { status: 'ok', expires: '2026-10-01', label: 'À jour' },
      securite:     { status: 'ok', expires: '2026-12-01', label: 'À jour' },
      jauge:        { status: 'ok', expires: '2028-01-01', label: 'À jour' },
    },
  },
]

export const SKIPPERS = [
  {
    id: 'skip-1', name: 'Jean-Marc Rossi', initials: 'JM', location: 'Marseille',
    rating: 4.9, missions: 38, rate: 180, available: true,
    color: 'bg-navy-100 text-navy-800',
    permis: ['Côtier', 'Hauturier', 'CRR', 'STCW'],
    boats: ['Voilier', 'Catamaran'], phone: '06 44 55 66 77',
    reviews: [
      { agency: 'Midi Nautisme', stars: 5, text: 'Ponctuel, clients très satisfaits.' },
      { agency: 'Midi Nautisme', stars: 5, text: 'Excellent contact avec les familles.' },
    ],
    availability: { busy: ['2026-07-05','2026-07-06','2026-07-07','2026-07-08','2026-07-09','2026-07-10','2026-07-11','2026-07-12'] },
  },
  {
    id: 'skip-2', name: 'Sophie Bernard', initials: 'SB', location: 'La Ciotat',
    rating: 4.6, missions: 22, rate: 150, available: true,
    color: 'bg-teal-50 text-teal-800',
    permis: ['Côtier', 'CRR'], boats: ['Voilier', 'Catamaran'], phone: '06 22 33 44 55',
    reviews: [{ agency: 'Midi Nautisme', stars: 5, text: 'Très à l\'aise avec les débutants.' }],
    availability: { busy: [] },
  },
  {
    id: 'skip-3', name: 'Thomas Lebrun', initials: 'TL', location: 'Toulon',
    rating: 5.0, missions: 61, rate: 220, available: false,
    color: 'bg-amber-50 text-amber-800',
    permis: ['Côtier', 'Hauturier', 'CRR', 'Yachtmaster'],
    boats: ['Voilier', 'Catamaran', 'Moteur'], phone: '06 77 88 99 00',
    reviews: [{ agency: 'Midi Nautisme', stars: 5, text: 'Le meilleur skipper qu\'on ait eu.' }],
    availability: { busy: [] },
  },
]

export const BOOKINGS = [
  {
    id: 'bk-1', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '6 adultes',
    start: '2026-07-04', end: '2026-07-11',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    options: { sup: { qty: 2 }, carbu: true },
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-2', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '3 adultes',
    start: '2026-07-11', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    options: { masque: { qty: 3 } },
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-3', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '2 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: true,
    draps: [],
    options: { annexe: true, franchise: { qty: 1 } },
    status: 'skipper-missing', color: 'amber',
    lastNightAboard: false,
  },
  {
    id: 'bk-4', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '5 adultes',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    options: { taud: true, sup: { qty: 1 } },
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-5', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-10', client: 'Mercier Olivier', phone: '06 55 11 99 22', guests: '4 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    options: { masque: { qty: 4 }, carbu: true },
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-6', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '3 adultes',
    start: '2026-08-08', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-7', boatId: 'mn-1', boatName: 'Dufour 360 GL — Yume', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '6 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-8', boatId: 'mn-2', boatName: 'Dufour 382 GL — Kalliste', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '2 adultes, 2 enfants',
    start: '2026-07-04', end: '2026-07-11',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-9', boatId: 'mn-2', boatName: 'Dufour 382 GL — Kalliste', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '5 adultes',
    start: '2026-07-11', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-10', boatId: 'mn-2', boatName: 'Dufour 382 GL — Kalliste', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '2 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-11', boatId: 'mn-2', boatName: 'Dufour 382 GL — Kalliste', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '7 adultes',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-12', boatId: 'mn-2', boatName: 'Dufour 382 GL — Kalliste', brand: 'midi-nautisme',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '3 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-13', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-10', client: 'Mercier Olivier', phone: '06 55 11 99 22', guests: '5 adultes',
    start: '2026-07-04', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-14', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '4 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-15', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '4 adultes, 1 enfant',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: true,
    draps: [],
    status: 'skipper-missing', color: 'amber',
    lastNightAboard: false,
  },
  {
    id: 'bk-16', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '4 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-17', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '4 adultes, 1 enfant',
    start: '2026-08-08', end: '2026-08-15',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-18', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '2 adultes',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-19', boatId: 'mn-3', boatName: 'Dufour 390 — Juleroga', brand: 'midi-nautisme',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '6 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: 'skip-3', skipperName: 'Thomas Lebrun', skipperInitials: 'TL',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-20', boatId: 'mn-4', boatName: 'Dufour 350', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '2 adultes',
    start: '2026-07-04', end: '2026-07-11',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-21', boatId: 'mn-4', boatName: 'Dufour 350', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '3 adultes',
    start: '2026-07-11', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-22', boatId: 'mn-4', boatName: 'Dufour 350', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '6 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: true,
    draps: [],
    status: 'skipper-missing', color: 'amber',
    lastNightAboard: true,
  },
  {
    id: 'bk-23', boatId: 'mn-4', boatName: 'Dufour 350', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '4 adultes, 1 enfant',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-24', boatId: 'mn-4', boatName: 'Dufour 350', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '3 adultes',
    start: '2026-08-08', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-25', boatId: 'mn-4', boatName: 'Dufour 350', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '3 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-26', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '2 adultes, 2 enfants',
    start: '2026-07-04', end: '2026-07-11',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-27', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '8 adultes',
    start: '2026-07-11', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-28', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '4 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: 'skip-2', skipperName: 'Sophie Bernard', skipperInitials: 'SB',
    needsSkipper: true,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-29', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '2 adultes, 2 enfants',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-30', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '2 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-31', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '6 adultes',
    start: '2026-08-08', end: '2026-08-15',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-32', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '2 adultes, 2 enfants',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-33', boatId: 'mn-5', boatName: 'Astrea 42 — Bôrev', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '2 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-34', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '2 adultes, 2 enfants',
    start: '2026-07-04', end: '2026-07-11',
    skipperId: 'skip-2', skipperName: 'Sophie Bernard', skipperInitials: 'SB',
    needsSkipper: true,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-35', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '4 adultes, 1 enfant',
    start: '2026-07-11', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-36', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '2 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-37', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '7 adultes',
    start: '2026-07-25', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-38', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '3 adultes',
    start: '2026-08-08', end: '2026-08-15',
    skipperId: 'skip-3', skipperName: 'Thomas Lebrun', skipperInitials: 'TL',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-39', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-7', client: 'Girard Sophie', phone: '06 44 11 22 33', guests: '2 adultes',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-40', boatId: 'mn-6', boatName: '460 — L\'After', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '4 adultes, 1 enfant',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: 'skip-3', skipperName: 'Thomas Lebrun', skipperInitials: 'TL',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-41', boatId: 'mn-7', boatName: 'Bali 4.1 · 6 cabines', brand: 'midi-nautisme',
    clientId: 'cli-10', client: 'Mercier Olivier', phone: '06 55 11 99 22', guests: '8 adultes',
    start: '2026-07-11', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-42', boatId: 'mn-7', boatName: 'Bali 4.1 · 6 cabines', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '4 adultes',
    start: '2026-07-18', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-43', boatId: 'mn-7', boatName: 'Bali 4.1 · 6 cabines', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '3 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-44', boatId: 'mn-7', boatName: 'Bali 4.1 · 6 cabines', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '3 adultes',
    start: '2026-08-08', end: '2026-08-15',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-45', boatId: 'mn-8', boatName: 'Elba 45 — Sirena', brand: 'midi-nautisme',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '7 adultes',
    start: '2026-07-04', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-46', boatId: 'mn-8', boatName: 'Elba 45 — Sirena', brand: 'midi-nautisme',
    clientId: 'cli-10', client: 'Mercier Olivier', phone: '06 55 11 99 22', guests: '7 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-47', boatId: 'mn-8', boatName: 'Elba 45 — Sirena', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '5 adultes',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-48', boatId: 'mn-8', boatName: 'Elba 45 — Sirena', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '4 adultes, 1 enfant',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-49', boatId: 'mn-8', boatName: 'Elba 45 — Sirena', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '6 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-50', boatId: 'mn-9', boatName: 'Dufour 48 — Petrel', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '4 adultes, 1 enfant',
    start: '2026-07-04', end: '2026-07-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-51', boatId: 'mn-9', boatName: 'Dufour 48 — Petrel', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '8 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-52', boatId: 'mn-9', boatName: 'Dufour 48 — Petrel', brand: 'midi-nautisme',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '2 adultes',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-53', boatId: 'mn-9', boatName: 'Dufour 48 — Petrel', brand: 'midi-nautisme',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '5 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-54', boatId: 'mn-9', boatName: 'Dufour 48 — Petrel', brand: 'midi-nautisme',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '5 adultes',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-55', boatId: 'mn-9', boatName: 'Dufour 48 — Petrel', brand: 'midi-nautisme',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '8 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-56', boatId: 'mn-10', boatName: 'MY40 — Calypso', brand: 'midi-nautisme',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '4 adultes',
    start: '2026-07-04', end: '2026-07-11',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-57', boatId: 'mn-10', boatName: 'MY40 — Calypso', brand: 'midi-nautisme',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '3 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-58', boatId: 'mn-10', boatName: 'MY40 — Calypso', brand: 'midi-nautisme',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '5 adultes',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-59', boatId: 'mn-10', boatName: 'MY40 — Calypso', brand: 'midi-nautisme',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '5 adultes',
    start: '2026-08-08', end: '2026-08-15',
    skipperId: 'skip-2', skipperName: 'Sophie Bernard', skipperInitials: 'SB',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-60', boatId: 'mn-10', boatName: 'MY40 — Calypso', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '2 adultes',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: 'skip-2', skipperName: 'Sophie Bernard', skipperInitials: 'SB',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-61', boatId: 'mn-11', boatName: 'Dufour 41 — Lou Calèu', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '3 adultes',
    start: '2026-07-04', end: '2026-07-18',
    skipperId: 'skip-2', skipperName: 'Sophie Bernard', skipperInitials: 'SB',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-62', boatId: 'mn-11', boatName: 'Dufour 41 — Lou Calèu', brand: 'midi-nautisme',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '8 adultes',
    start: '2026-07-18', end: '2026-07-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [{ name: 'Grand lit 160×200', qty: 1, unit: 'jeu' }],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-63', boatId: 'mn-11', boatName: 'Dufour 41 — Lou Calèu', brand: 'midi-nautisme',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '4 adultes',
    start: '2026-07-25', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-64', boatId: 'mn-11', boatName: 'Dufour 41 — Lou Calèu', brand: 'midi-nautisme',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '5 adultes',
    start: '2026-08-01', end: '2026-08-08',
    skipperId: 'skip-3', skipperName: 'Thomas Lebrun', skipperInitials: 'TL',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-65', boatId: 'mn-11', boatName: 'Dufour 41 — Lou Calèu', brand: 'midi-nautisme',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '5 adultes',
    start: '2026-08-15', end: '2026-08-22',
    skipperId: 'skip-1', skipperName: 'Jean-Marc Rossi', skipperInitials: 'JM',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-66', boatId: 'mn-11', boatName: 'Dufour 41 — Lou Calèu', brand: 'midi-nautisme',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '8 adultes',
    start: '2026-08-22', end: '2026-08-29',
    skipperId: 'skip-2', skipperName: 'Sophie Bernard', skipperInitials: 'SB',
    needsSkipper: true,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: true,
  },
  {
    id: 'bk-67', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '3 adultes',
    start: '2026-07-19', end: '2026-07-19',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-68', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '4 adultes',
    start: '2026-07-26', end: '2026-07-26',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-69', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '4 adultes',
    start: '2026-07-28', end: '2026-07-29',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-70', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '5 adultes',
    start: '2026-08-05', end: '2026-08-05',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-71', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '4 adultes',
    start: '2026-08-22', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-72', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-2', client: 'Bernard Laurent', phone: '07 11 22 33 44', guests: '2 adultes, 2 enfants',
    start: '2026-08-25', end: '2026-08-25',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-73', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '2 adultes',
    start: '2026-08-10', end: '2026-08-11',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-74', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '2 adultes',
    start: '2026-07-23', end: '2026-07-23',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-75', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-3', client: 'Martin Pierre', phone: '06 55 44 33 22', guests: '2 adultes, 2 enfants',
    start: '2026-08-06', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-76', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '3 adultes',
    start: '2026-08-21', end: '2026-08-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-77', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-10', client: 'Mercier Olivier', phone: '06 55 11 99 22', guests: '2 adultes',
    start: '2026-07-22', end: '2026-07-22',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-78', boatId: 'lm-1', boatName: 'Tempest 505', brand: 'locamotors',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '5 adultes',
    start: '2026-08-26', end: '2026-08-27',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-79', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '5 adultes',
    start: '2026-08-31', end: '2026-09-02',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-80', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '3 adultes',
    start: '2026-08-26', end: '2026-08-28',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-81', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-1', client: 'Moreau Jean', phone: '06 12 34 56 78', guests: '3 adultes',
    start: '2026-07-09', end: '2026-07-09',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-82', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '2 adultes, 2 enfants',
    start: '2026-08-13', end: '2026-08-13',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-83', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '2 adultes',
    start: '2026-08-01', end: '2026-08-01',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-84', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '4 adultes',
    start: '2026-08-07', end: '2026-08-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-85', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '5 adultes',
    start: '2026-07-04', end: '2026-07-04',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-86', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '5 adultes',
    start: '2026-08-30', end: '2026-08-30',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-87', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '2 adultes',
    start: '2026-07-08', end: '2026-07-08',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-88', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '3 adultes',
    start: '2026-08-27', end: '2026-08-27',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-89', boatId: 'lm-2', boatName: 'BSC 65', brand: 'locamotors',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '2 adultes, 2 enfants',
    start: '2026-07-18', end: '2026-07-19',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-90', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '5 adultes',
    start: '2026-08-03', end: '2026-08-03',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-91', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '5 adultes',
    start: '2026-08-13', end: '2026-08-13',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-92', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-6', client: 'Roche Antoine', phone: '06 88 77 66 55', guests: '4 adultes',
    start: '2026-07-13', end: '2026-07-13',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-93', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-10', client: 'Mercier Olivier', phone: '06 55 11 99 22', guests: '2 adultes',
    start: '2026-08-12', end: '2026-08-12',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-94', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '2 adultes',
    start: '2026-07-07', end: '2026-07-07',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-95', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-4', client: 'Legrand François', phone: '06 77 88 99 00', guests: '4 adultes',
    start: '2026-08-17', end: '2026-08-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-96', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '2 adultes, 2 enfants',
    start: '2026-08-18', end: '2026-08-18',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-97', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-8', client: 'Lemoine Thibault', phone: '06 99 22 33 44', guests: '5 adultes',
    start: '2026-08-02', end: '2026-08-02',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-98', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '2 adultes, 2 enfants',
    start: '2026-07-16', end: '2026-07-16',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-99', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-5', client: 'Faure Christine', phone: '06 33 22 11 00', guests: '2 adultes',
    start: '2026-07-05', end: '2026-07-06',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
  {
    id: 'bk-100', boatId: 'lm-3', boatName: 'Pacific Craft 730', brand: 'locamotors',
    clientId: 'cli-9', client: 'Perrin Claire', phone: '06 66 77 88 99', guests: '4 adultes',
    start: '2026-08-25', end: '2026-08-26',
    skipperId: null, skipperName: null, skipperInitials: null,
    needsSkipper: false,
    draps: [],
    status: 'confirmed', color: 'teal',
    lastNightAboard: false,
  },
]

export const TECHNICIANS = [
  {
    id: 'tech-1', name: 'Karim B.', phone: '06 11 22 33 44', base: 'Vieux-Port',
    assignedBoats: ['mn-1', 'mn-2', 'mn-3', 'mn-4', 'mn-9'],
    tasks: {
      'mn-1': [
        { id: 't1', label: 'Nettoyage cabines', done: true },
        { id: 't2', label: 'Draps posés (3 jeux)', done: true },
        { id: 't3', label: 'Inventaire vérifié', done: true },
        { id: 't4', label: 'Équipements sécurité', done: false },
      ],
    },
  },
  {
    id: 'tech-2', name: 'Léa M.', phone: '06 55 66 77 88', base: 'Vieux-Port',
    assignedBoats: ['mn-3', 'mn-4', 'lm-1', 'mn-10'],
    tasks: {
      'lm-1': [
        { id: 't5', label: 'Nettoyage cockpit', done: true },
        { id: 't6', label: 'Inventaire vérifié', done: false },
        { id: 't7', label: 'Carburant plein', done: false },
      ],
    },
  },
  {
    id: 'tech-3', name: 'Marc D.', phone: '06 99 88 77 66', base: 'Port Corbières',
    assignedBoats: ['mn-5', 'mn-6', 'mn-7', 'mn-8', 'mn-11'],
    tasks: {
      'mn-5': [
        { id: 't8', label: 'Nettoyage cabines (4)', done: false },
        { id: 't9', label: 'Draps posés', done: false },
        { id: 't10', label: 'Équipements sécurité', done: false },
      ],
    },
  },
]

export const PRICING_PERIODS = [
  { id: 'period-1', label: 'Basse saison', start: '2026-01-01', end: '2026-06-27', color: '#0F7D57', rhythm: 'free' },
  { id: 'period-2', label: 'Moyenne saison', start: '2026-06-28', end: '2026-07-04', color: '#B36A0A', rhythm: 'free' },
  { id: 'period-3', label: 'Haute saison', start: '2026-07-05', end: '2026-08-29', color: '#B02020', rhythm: 'weekly-sat' },
  { id: 'period-4', label: 'Moyenne saison (arrière-saison)', start: '2026-08-30', end: '2026-09-19', color: '#B36A0A', rhythm: 'free' },
  { id: 'period-5', label: 'Basse saison (fin d\'année)', start: '2026-09-20', end: '2026-12-31', color: '#0F7D57', rhythm: 'free' },
]

// Grille tarifaire : prix par semaine, par bateau, par période
export const BOAT_PRICES = {
  'mn-1':  { 'period-1': 1400, 'period-2': 1900, 'period-3': 2600, 'period-4': 1900, 'period-5': 1400 },
  'mn-2':  { 'period-1': 1500, 'period-2': 2000, 'period-3': 2750, 'period-4': 2000, 'period-5': 1500 },
  'mn-3':  { 'period-1': 1600, 'period-2': 2150, 'period-3': 2950, 'period-4': 2150, 'period-5': 1600 },
  'mn-4':  { 'period-1': 1300, 'period-2': 1750, 'period-3': 2400, 'period-4': 1750, 'period-5': 1300 },
  'mn-5':  { 'period-1': 2400, 'period-2': 3200, 'period-3': 4400, 'period-4': 3200, 'period-5': 2400 },
  'mn-6':  { 'period-1': 3200, 'period-2': 4300, 'period-3': 5900, 'period-4': 4300, 'period-5': 3200 },
  'mn-7':  { 'period-1': 2600, 'period-2': 3500, 'period-3': 4800, 'period-4': 3500, 'period-5': 2600 },
  'mn-8':  { 'period-1': 2700, 'period-2': 3600, 'period-3': 4950, 'period-4': 3600, 'period-5': 2700 },
  'mn-9':  { 'period-1': 2200, 'period-2': 2950, 'period-3': 4050, 'period-4': 2950, 'period-5': 2200 },
  'mn-10': { 'period-1': 2300, 'period-2': 3100, 'period-3': 4250, 'period-4': 3100, 'period-5': 2300 },
  'mn-11': { 'period-1': 1700, 'period-2': 2300, 'period-3': 3150, 'period-4': 2300, 'period-5': 1700 },
  'lm-1':  { 'period-1': 900,  'period-2': 1200, 'period-3': 1650, 'period-4': 1200, 'period-5': 900 },
  'lm-2':  { 'period-1': 1100, 'period-2': 1450, 'period-3': 2000, 'period-4': 1450, 'period-5': 1100 },
  'lm-3':  { 'period-1': 1200, 'period-2': 1600, 'period-3': 2200, 'period-4': 1600, 'period-5': 1200 },
}

export const CONTRACT_TEMPLATES = [
  {
    id: 'tpl-standard',
    label: 'Contrat standard (voilier / catamaran)',
    body: `CONTRAT DE LOCATION DE BATEAU DE PLAISANCE

Entre les soussignés :

{{company_name}}
{{company_port}}
Tél : {{company_phone}} — Email : {{company_email}}
Ci-après dénommé « le Loueur »,

Et :

{{client_prenom}} {{client_nom}}
Né(e) le {{client_naissance}}, de nationalité {{client_nationalite}}
Pièce d'identité n° {{client_piece_numero}}
Permis {{client_permis_type}} n° {{client_permis_numero}}
Téléphone : {{client_tel}} — Email : {{client_email}}
Ci-après dénommé « le Locataire »,

Il a été convenu ce qui suit :

Article 1 — Objet du contrat
Le Loueur met à disposition du Locataire le bateau {{boat_name}} ({{boat_type}}, {{boat_length}} m, capacité {{boat_capacite}} personnes), pour la période du {{start_date}} au {{end_date}}.

Article 2 — Équipage
Nombre de personnes à bord : {{guests}}
Skipper : {{skipper_info}}

Article 3 — Prix et caution
Prix de la location : {{price}}
Montant de la caution : {{caution_montant}} (mode : {{caution_mode}})

Article 4 — Options et prestations complémentaires
{{options_list}}

Article 5 — Obligations du Locataire
Le Locataire s'engage à restituer le bateau dans l'état où il l'a reçu, à respecter les règles de sécurité maritime en vigueur, et à signaler immédiatement tout incident survenu pendant la location.

Fait à Marseille, le {{today}}.

Signature du Loueur                                    Signature du Locataire`,
  },
  {
    id: 'tpl-day',
    label: 'Contrat journée (semi-rigide / moteur)',
    body: `CONTRAT DE LOCATION — SORTIE À LA JOURNÉE

Entre les soussignés :

{{company_name}}
{{company_port}}
Tél : {{company_phone}} — Email : {{company_email}}
Ci-après dénommé « le Loueur »,

Et :

{{client_prenom}} {{client_nom}}
Permis {{client_permis_type}} n° {{client_permis_numero}}
Téléphone : {{client_tel}} — Email : {{client_email}}
Ci-après dénommé « le Locataire »,

Article 1 — Objet
Location du bateau {{boat_name}} ({{boat_type}}, {{boat_length}} m) du {{start_date}} au {{end_date}}.

Article 2 — Prix et caution
Prix : {{price}} — Caution : {{caution_montant}} ({{caution_mode}})

Article 3 — Options
{{options_list}}

Article 4 — Sécurité
Le Locataire déclare avoir pris connaissance des consignes de sécurité et s'engage à les respecter.

Fait à Marseille, le {{today}}.

Signature du Loueur                                    Signature du Locataire`,
  },
]

export const OPTIONS_CATALOG = [
  { id: 'skipper', label: 'Skipper', icon: 'Anchor', hasSub: true, price: 180, unit: '/ jour', active: true, description: 'Skipper professionnel pour la durée de la location' },
  { id: 'draps', label: 'Draps & linge', icon: 'Shirt', hasSub: true, price: 15, unit: '/ jeu', active: true, description: 'Jeu de draps et serviettes par cabine' },
  { id: 'carbu', label: 'Carburant inclus', icon: 'Fuel', hasSub: false, price: 80, unit: 'forfait', active: true, description: 'Plein de carburant inclus au départ' },
  { id: 'sup', label: 'SUP', icon: 'Waves', hasSub: true, price: 25, unit: '/ semaine', active: true, description: 'Paddle gonflable avec pagaie' },
  { id: 'annexe', label: 'Annexe / zodiac', icon: 'Sailboat', hasSub: false, price: 60, unit: '/ semaine', active: true, description: 'Annexe avec moteur hors-bord' },
  { id: 'taud', label: 'Taud de soleil', icon: 'Sun', hasSub: false, price: 20, unit: '/ semaine', active: true, description: 'Taud de soleil pour le cockpit' },
  { id: 'masque', label: 'Masque & tuba', icon: 'Glasses', hasSub: true, price: 8, unit: '/ jeu', active: true, description: 'Équipement snorkeling par personne' },
  { id: 'franchise', label: 'Franchise réduite', icon: 'ShieldCheck', hasSub: true, price: 90, unit: 'forfait', active: true, description: 'Réduction de la franchise en cas de dommage' },
  { id: 'wifi', label: 'WiFi satellite', icon: 'Wifi', hasSub: false, price: 45, unit: '/ semaine', active: false, description: 'Connexion internet satellite à bord' },
  { id: 'menage', label: 'Ménage fin de séjour', icon: 'SprayCan', hasSub: false, price: 70, unit: 'forfait', active: false, description: 'Nettoyage complet en fin de location' },
]

export const DOC_LABELS = {
  francisation: 'Francisation',
  assurance:    'Assurance',
  securite:     'Carnet sécurité',
  jauge:        'Jauge officielle',
}
